/*
 * File: app/store/Menu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.store.Menu', {
    extend: 'Ext.data.Store',
    alias: 'store.menu',

    requires: [
        'Ubibus.model.Menu'
    ],

    config: {
        data: [
            {
                item: 'Linhas',
                view: 'linha'
            },
            {
                item: 'Pontos',
                view: 'ponto'
            },
            {
                item: 'Onibus',
                view: 'onibus'
            },
            {
                item: 'Empresas',
                view: 'empresa'
            }
        ],
        model: 'Ubibus.model.Menu',
        storeId: 'menu'
    }
});