/*
 * File: app/store/Onibus.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.store.Onibus', {
    extend: 'Ext.data.Store',
    alias: 'store.onibus',

    requires: [
        'Ubibus.model.Onibus'
    ],

    config: {
        model: 'Ubibus.model.Onibus',
        storeId: 'onibus',
        proxy: {
            type: 'ajax',
            api: {
                create: 'php/onibus/criaOnibus.php',
                read: 'php/onibus/listaOnibus.php',
                update: 'php/onibus/atualizaOnibus.php',
                destroy: 'php/onibus/deletaOnibus.php'
            },
            reader: {
                type: 'json',
                rootProperty: 'onibus'
            },
            writer: {
                type: 'json',
                writeAllFields: false,
                encode: true,
                rootProperty: 'onibus'
            }
        }
    }
});