/*
 * File: app/store/Usuario.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.store.Usuario', {
    extend: 'Ext.data.Store',
    alias: 'store.usuario',

    requires: [
        'Ubibus.model.Usuario'
    ],

    config: {
        autoSync: false,
        model: 'Ubibus.model.Usuario',
        storeId: 'usuario',
        proxy: {
            type: 'ajax',
            api: {
                create: 'php/usuario/criaUsuario.php',
                read: 'php/usuario/listaUsuario.php',
                update: 'php/usuario/atualizaUsuario.php',
                destroy: 'php/usuario/deletaUsuario.php'
            },
            reader: {
                type: 'json',
                rootProperty: 'usuario'
            },
            writer: {
                type: 'json',
                writeAllFields: false,
                encode: true,
                rootProperty: 'usuario'
            }
        }
    }
});