/*
 * File: app/view/Empresa.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.view.Empresa', {
    extend: 'Ext.dataview.List',
    alias: 'widget.empresa',

    config: {
        id: 'empresa',
        ui: 'round',
        emptyText: 'Não há dados cadastrados!',
        store: 'empresa',
        grouped: true,
        onItemDisclosure: true,
        indexBar: true,
        itemTpl: [
            '<div>{nome}</div>'
        ],
        listeners: [
            {
                fn: 'onEmpresaActivate',
                event: 'activate'
            },
            {
                fn: 'onEmpresaDeactivate',
                event: 'deactivate'
            }
        ]
    },

    onEmpresaActivate: function(container, newActiveItem, oldActiveItem, eOpts) {
        Ext.getCmp('btnNavAdicionarEmpresa').setHidden(false);
    },

    onEmpresaDeactivate: function(container, newActiveItem, oldActiveItem, eOpts) {
        Ext.getCmp('btnNavAdicionarEmpresa').setHidden(true);
    }

});