/*
 * File: app/view/ListaLinhas.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.view.ListaLinhas', {
    extend: 'Ext.dataview.List',
    alias: 'widget.listalinhas',

    config: {
        id: 'listalinhas',
        style: 'font-size:85%;padding:0;',
        ui: 'round',
        emptyText: 'Não há linhas cadastradas!',
        store: 'itinerarios',
        onItemDisclosure: false,
        itemTpl: [
            '<div><b>{numero}</b> : {origem} - {destino}</div>',
            '<tpl if="via">',
            '    <div><b style="visibility:hidden;">{numero}</b>   <span style="font-style: italic;font-size:80%;">(Via {via}<span>)</div>',
            '</tpl>'
        ]
    }

});