/*
 * File: app/view/OnibusForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.view.OnibusForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.onibusform',

    config: {
        id: 'onibusForm',
        items: [
            {
                xtype: 'label',
                html: 'status da pesquisa',
                id: 'lblOnibusStatusPesquisa',
                style: 'text-align:center;margin-top:-10px;font-style: italic;'
            },
            {
                xtype: 'spacer',
                height: 5
            },
            {
                xtype: 'container',
                id: 'formOnibus',
                items: [
                    {
                        xtype: 'segmentedbutton',
                        id: 'opcoesOnibus',
                        itemId: 'mysegmentedbutton1',
                        defaults: {
                            disabled: false
                        },
                        allowDepress: true,
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnOnibusOcorrencia',
                                iconCls: 'info',
                                iconMask: true,
                                text: ''
                            },
                            {
                                xtype: 'button',
                                hidden: true,
                                id: 'btnOnibusLocalizacao',
                                iconCls: 'locate',
                                iconMask: true,
                                text: ''
                            },
                            {
                                xtype: 'button',
                                hidden: true,
                                id: 'btnOnibusHidden'
                            },
                            {
                                xtype: 'button',
                                id: 'btnOnibusFavorito',
                                iconCls: 'star',
                                iconMask: true,
                                text: ''
                            },
                            {
                                xtype: 'button',
                                hidden: true,
                                id: 'btnOnibusDetalhe',
                                iconCls: 'bookmarks',
                                iconMask: true,
                                text: ''
                            },
                            {
                                xtype: 'button',
                                id: 'btnOnibusEditar',
                                itemId: 'mybutton10',
                                iconCls: 'compose',
                                iconMask: true,
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        id: 'infoOnibus',
                        defaults: {
                            disabled: false
                        },
                        instructions: 'Dados do veículo',
                        title: 'Informações',
                        items: [
                            {
                                xtype: 'textfield',
                                disabled: true,
                                id: 'txtNumeroOnibus',
                                labelWidth: '45%',
                                name: 'numero',
                                placeHolder: 'Número do ônibus'
                            },
                            {
                                xtype: 'selectfield',
                                disabled: true,
                                id: 'selectEmpresa',
                                labelWidth: '45%',
                                name: 'id_empresa',
                                placeHolder: 'Empresa',
                                displayField: 'nome',
                                store: 'empresa',
                                valueField: 'id_empresa'
                            },
                            {
                                xtype: 'checkboxfield',
                                disabled: true,
                                id: 'checkAdaptado',
                                label: 'Veiculo adaptado',
                                labelWidth: '75%',
                                name: 'adaptado'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        id: 'btnSalvarOnibus',
                        ui: 'confirm',
                        iconMask: true,
                        text: 'Salvar'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onOpcoesOnibusToggle',
                event: 'toggle',
                delegate: '#opcoesOnibus'
            }
        ]
    },

    onOpcoesOnibusToggle: function(segmentedbutton, button, isPressed, eOpts) {
        //Variavel que habilita os campos do formulario apenas quando 'btnOnibusEditar' estiver ativo
        var habilitaCamposForm = true;

        switch(button.id)
        {
            case 'btnOnibusLocalizacao':
            //TODO
            break;
            case 'btnOnibusOcorrencia':
            //TODO
            break;
            case 'btnOnibusEditar':
            habilitaCamposForm = !isPressed;
            break;
            case 'btnOnibusDetalhe':
            //TODO
            break;
            default:         
        }

        //Habilita os campos para edição
        Ext.getCmp('selectEmpresa').setDisabled(habilitaCamposForm);
        Ext.getCmp('checkAdaptado').setDisabled(habilitaCamposForm);

        //Exibe o botão de 'Salvar'
        Ext.getCmp('btnSalvarOnibus').setHidden(habilitaCamposForm);
    }

});