/*
 * File: app/view/Onibus.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.view.Onibus', {
    extend: 'Ext.form.Panel',
    alias: 'widget.onibus',

    config: {
        id: 'onibusView',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                hidden: true,
                id: 'toolbarOnibus',
                title: 'Onibus'
            },
            {
                xtype: 'fieldset',
                id: 'fieldPesquisaOnibus',
                instructions: 'Efetue uma pesquisa :)',
                title: 'Pesquisa',
                items: [
                    {
                        xtype: 'searchfield',
                        id: 'numeroOnibus',
                        labelWidth: '45%',
                        name: 'numeroOnibus',
                        placeHolder: 'Número do ônibus'
                    }
                ]
            },
            {
                xtype: 'button',
                id: 'btnOnibusPesquisar',
                ui: 'action',
                iconAlign: 'center',
                iconMask: true,
                text: 'Pesquisar'
            }
        ],
        listeners: [
            {
                fn: 'onMysearchfield1Clearicontap',
                event: 'clearicontap',
                delegate: '#numeroOnibus'
            }
        ]
    },

    onMysearchfield1Clearicontap: function(textfield, e, eOpts) {
        //Limpa os campos do formulário
        this.reset();

        //Altera o campo instructions do fieldset
        Ext.getCmp('fieldPesquisaOnibus').setInstructions('Efetue uma pesquisa!   :)');
    }

});