/*
 * File: app/view/PontoDetalhe.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.view.PontoDetalhe', {
    extend: 'Ext.form.Panel',
    alias: 'widget.pontodetalhe',

    requires: [
        'Ubibus.view.ListaLinhas'
    ],

    config: {
        id: 'pontoDetalhe',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'label',
                hidden: true,
                html: 'status da pesquisa',
                id: 'lblOnibusStatusPesquisa',
                style: 'text-align:center;margin-top:-10px;font-style: italic;font-size:80%;font-weight:bold;'
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'segmentedbutton',
                id: 'opcoesPontoLinha',
                itemId: 'mysegmentedbutton1',
                defaults: {
                    disabled: false
                },
                allowDepress: true,
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'btnPontoOcorrencia',
                        iconCls: 'info',
                        iconMask: true,
                        text: ''
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'btnPontoHidden'
                    },
                    {
                        xtype: 'button',
                        id: 'btnPontoFavorito',
                        iconCls: 'star',
                        iconMask: true,
                        text: ''
                    },
                    {
                        xtype: 'button',
                        id: 'btnPontoEditar',
                        iconCls: 'search',
                        iconMask: true,
                        text: ''
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'btnPontoPesquisarLinha',
                        iconCls: 'search',
                        iconMask: true,
                        text: ''
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                height: 145,
                hidden: true,
                id: 'containerPontoInfo',
                style: '',
                items: [
                    {
                        xtype: 'fieldset',
                        id: 'infoPontoLinha',
                        defaults: {
                            disabled: false
                        },
                        hideOnMaskTap: false,
                        title: 'Pesquisar',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'txtItinerarioNumeroLinha',
                                itemId: 'mytextfield5',
                                labelWidth: '45%',
                                name: 'numero',
                                placeHolder: 'Número da linha'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'btnItinerarioSugerir',
                        style: 'margin-top:-20px;',
                        text: 'Sugerir'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                id: 'containerPontoLinhas',
                style: 'margin:-10px;',
                ui: '',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'listalinhas',
                        style: 'font-size:80%;'
                    },
                    {
                        xtype: 'label',
                        docked: 'top',
                        html: 'Linhas servindo este ponto',
                        id: 'lblPontoDetalheLinhasServindoPonto',
                        style: 'text-align:left;font-style: italic;font-size:85%;font-weight:bold;margin-top:20px;margin-left:15px;'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onOpcoesOnibusToggle',
                event: 'toggle',
                delegate: '#opcoesPontoLinha'
            },
            {
                fn: 'onTxtNumeroLinhaKeyup',
                event: 'keyup',
                delegate: '#txtItinerarioNumeroLinha'
            },
            {
                fn: 'onTxtNumeroLinhaClearicontap',
                event: 'clearicontap',
                delegate: '#txtItinerarioNumeroLinha'
            }
        ]
    },

    onOpcoesOnibusToggle: function(segmentedbutton, button, isPressed, eOpts) {
        //Variavel que habilita os campos do formulario apenas quando 'btnPontoEditar' estiver ativo
        var habilitaCamposForm = true;
        switch(button.id)
        {
            case 'btnPontoLocalizacao':
            //TODO
            break;
            case 'btnPontoOcorrencia':
            //TODO
            break;
            case 'btnPontoEditar':
            habilitaCamposForm = !isPressed;
            break;
            case 'btnPontoDetalhe':
            //TODO
            break;
            default:         
        }

        //Exibe o botão de 'Salvar'
        Ext.getCmp('containerPontoInfo').setHidden(habilitaCamposForm);

        var store = Ext.getCmp('listalinhas').getStore();
        store.clearFilter();

        Ext.getCmp('txtItinerarioNumeroLinha').setValue('');
        Ext.getCmp('btnItinerarioSugerir').setHidden(true);
    },

    onTxtNumeroLinhaKeyup: function(textfield, e, eOpts) {
        var queryString = textfield.getValue();

        var store = Ext.getCmp('listalinhas').getStore();
        store.clearFilter();

        if(queryString){
            var thisRegEx = new RegExp(queryString, "i");

            store.filterBy(function(record) {
                if (thisRegEx.test(record.get('numero')) ||
                thisRegEx.test(record.get('origem')) ||
                thisRegEx.test(record.get('destino'))) {
                    return true;
                };
                return false;
            });
        }else{
            Ext.getCmp('btnItinerarioSugerir').setHidden(true);
        }

        var total = store.getCount();
        if(total > 0){
            Ext.getCmp('btnItinerarioSugerir').setHidden(true);
        }else{
            Ext.getCmp('btnItinerarioSugerir').setHidden(false);

        }
    },

    onTxtNumeroLinhaClearicontap: function(textfield, e, eOpts) {
        var store = Ext.getCmp('listalinhas').getStore();
        store.clearFilter();

        Ext.getCmp('btnItinerarioSugerir').setHidden(true);
    }

});