/*
 * File: app/model/Engarrafamento.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.model.Engarrafamento', {
    extend: 'Ext.data.Model',
    alias: 'model.engarrafamento',

    config: {
        fields: [
            {
                name: 'id_engarrafamento'
            },
            {
                name: 'motivo_engarrafamento'
            },
            {
                name: 'id_ponto'
            }
        ]
    }
});