/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Empresa',
        'Onibus',
        'Posicao',
        'Ponto',
        'Linha',
        'Menu',
        'Itinerario',
        'Ocorrencia',
        'Engarrafamento'
    ],
    stores: [
        'Empresas',
        'Onibus',
        'Pontos',
        'Linha',
        'Menu',
        'Itinerarios',
        'Engarrafamentos'
    ],
    views: [
        'Empresa',
        'Onibus',
        'mapa',
        'Linha',
        'Ocorrencia',
        'Ponto',
        'Usuario',
        'LinhaMapa',
        'MenuPontos',
        'Viewport',
        'OnibusForm',
        'LinhaForm',
        'NavHome',
        'Menu',
        'Indicadores',
        'ToolbarMapa',
        'PontoDetalhe',
        'ListaLinhas'
    ],
    controllers: [
        'Main'
    ],
    name: 'Ubibus',

    launch: function() {

        Ext.create('Ubibus.view.Viewport', {fullscreen: true});
    }

});
